default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DATABASE_HOST"] %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "library_management_development" } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "library_management_test" } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
